CREATE SCHEMA IF NOT EXISTS NOTIFICATIONS;

SET SEARCH_PATH = 'NOTIFICATIONS';

CREATE TABLE IF NOT EXISTS NOTIFICATION (
    ID SERIAL PRIMARY KEY,
    MESSAGE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL CHECK (TYPE IN ('NEW_RESULT', 'RESERVATION_PENDING', 'RESERVATION_CONFIRMED', 'RESERVATION_REJECTED')),
    USER_ID INTEGER NOT NULL,
    READ BOOLEAN DEFAULT FALSE,
    URL VARCHAR(255) NOT NULL,
);